### ISSUE TITLE
It should NOT be used in production.

### ISSUE THREAD

**Issue by thomasmodeneis** [mschoch/elasticsearch-river-couchbase#1]
Hi,

Since this is a project that is about 5 years old and I still see the get off message on your readme file, I need to ask: Is there any plans/deadlines for when you will be supporting production code ?  If not, Is there any other recommended module for this task ?

Cheers.

**Comment by mschoch** [comment]
This particular codebase is quite old.  I think Elasticsearch removed the whole "river" feature/capability that it relies on.  So it wouldn't even be possible to use this approach in the future.

The current solution to integration Couchbase with Elasticsearch is:

https://github.com/couchbaselabs/elasticsearch-transport-couchbase
